
name: 'backhand_developer'
version: '1.0.0'
config-version: 2

profile: 'backhand_developer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  start_date: '2000-01-03'

models:
  backhand_developer:
    +required_tests: {"unique.*|not_null": 1}

on-run-start: "{{ fix_missing_ranking_dates() }}"
