version: 2

models:
  - name: utl_ranking_dates
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: source('dev', 'rankings_raw')
          config: 
            severity: warn
    columns:
      - name: date_week
        tests:
          - not_null
          - unique