version: 2

exposures:
  - name: ranking_streamgraph
    label: ATP ranking streamgraph
    type: dashboard
    maturity: low
    url: https://backhand.querytechnology.net
    description: >
      Work in progress...
    depends_on:
      - ref('input_streamgraph')
    owner:
      name: Wouter Diesveld
      email: wouter@tinyqueries.com