version: 2

exposures:
  - name: ranking_streamgraph
    label: ATP ranking streamgraph
    type: dashboard
    maturity: medium
    depends_on:
      - ref('input_streamgraph')
    owner:
      name: Wouter Diesveld
      email: wouter@tinyqueries.com