version: 2

sources:
  - name: dev
    database: backhand_developer
    schema: dev
    tables:
      - name: rankings_raw
        columns:
          - name: date 
            tests:
              - not_null
              - unique
          - name: rankings
            tests: 
              - not_null

models:
  - name: stg_rankings
    columns:
    - name: player_name
      tests: 
        - not_null
    - name: player_id
      tests:
        - not_null
        - relationships:
            to: ref('stg_players')
            field: player_id
  - name: stg_players
    columns:
    - name: player_id
      tests:
        - not_null
        - unique
        - relationships:
            to: ref('stg_rankings')
            field: player_id