version: 2

sources:
  - name: dev
    database: backhand_developer
    schema: dev
    loader: python script
    tables:
      - name: rankings_raw
        description: "{{ doc('source_rankings_raw') }}"
        loaded_at_field: CAST(date as TIMESTAMP)
        freshness:
          warn_after:
            count: 7
            period: day
        columns:
          - name: date 
            tests:
              - not_null
              - unique
          - name: rankings
            description: JSON blob coming from external api
            tests: 
              - not_null

models:
  - name: stg_rankings
    description: Main table to select ranking data from
    config:
      tags: weekly
    columns:
    - name: player_name
      tests: 
        - not_null
    - name: player_id
      tests:
        - not_null
        - relationships:
            to: ref('stg_players')
            field: player_id
    - name: player_rank
      tests:
        - not_null
        - assert_greater_than_zero
  - name: stg_players
    description: Contains all tennis players found in ranking data
    config:
      tags: weekly
    columns:
    - name: player_id
      tests:
        - not_null
        - unique
        - relationships:
            to: ref('stg_rankings')
            field: player_id

