version: 2

models:
  - name: stg_rankings
    description: Main table to select ranking data from
    config:
      tags: weekly
    columns:
    - name: id
      tests:
        - not_null
        - unique
    - name: player_name
      tests: 
        - not_null
    - name: player_id
      tests:
        - not_null
        - relationships:
            to: ref('int_players')
            field: player_id
    - name: player_rank
      tests:
        - not_null
        - assert_greater_than_zero
    - name: player_points
      tests:
        - not_null
        - assert_greater_than_zero


